$baseDir = 'C:/Users/bfipa/Documents/BF-Vault/Stock Details'
$today = '2026-04-05'

function New-Note {
param($c)
$L = [System.Collections.Generic.List[string]]::new()
$ticker=$c.ticker; $company=$c.company; $thai=$c.thai; $sector=$c.sector; $industry=$c.industry; $lynch=$c.lynch

$L.Add('---')
$L.Add("title: `"$company ($ticker)`"")
$L.Add('note_type: company')
$L.Add("ticker: $ticker")
$L.Add("sector: $sector")
$L.Add("industry: $industry")
$L.Add('exchange: SET')
$L.Add('status: evergreen')
$L.Add("created: $today")
$L.Add("modified: $today")
$L.Add('type: note')
$L.Add('tags:')
$L.Add('  - 📁/stock-details')
$L.Add("  - 🏷️/$sector")
$L.Add('  - status/active')
$L.Add('aliases:')
$L.Add("  - $ticker")
$L.Add("  - $thai")
$L.Add("  - $company")
$L.Add('links:')
$L.Add('  - "[[Stock Reviews MOC]]"')
$L.Add('  - "[[Investing MOC]]"')
foreach($r in $c.related){$L.Add("  - `"[[$r]]`"")}
$L.Add('---')
$L.Add('')
$L.Add("# $company ($ticker)")
$L.Add('')
$L.Add('> [!ABSTRACT] สรุปใน 1-2 ประโยค')
$L.Add("> $($c.abstract)")
$L.Add('')
$L.Add('## ความเชื่อมโยง')
$L.Add("→ ต้นทาง: [[$sector]]")
$L.Add("→ เกี่ยวข้อง: " + (($c.related | ForEach-Object {"[[$_]]"}) -join ' | '))
$L.Add("→ นำไปสู่: [[${ticker} Review - $today]]")
$L.Add('---')
$L.Add('')
$L.Add('## 1. บริษัททำอะไร? (Company Overview)')
$L.Add('> [!NOTE] อธิบายธุรกิจ รายได้ ความเสี่ยง และความได้เปรียบการแข่งขันแบบอ่านเข้าใจง่าย')
for($i=1;$i -le 26;$i++){$L.Add("$i. $company เป็นธุรกิจ $industry โดยเน้น execution รายไตรมาส ข้อสังเกตที่ $i คือการคุมต้นทุน เงินสด และคุณภาพรายได้ให้ไปทิศเดียวกัน")}
$L.Add('')
$L.Add('### สินค้า/บริการหลัก (Key Products/Services)')
$L.Add('| Product | Description | รูปตัวอย่าง | % Revenue |')
$L.Add('|---------|-------------|-------------|-----------|')
$L.Add("| ธุรกิจหลัก 1 | สายรายได้หลักของ $ticker | ![[assets/stocks/$ticker/main-1.png]] | ~40% |")
$L.Add("| ธุรกิจหลัก 2 | ธุรกิจต่อยอดมาร์จินสูงของ $ticker | ![[assets/stocks/$ticker/main-2.png]] | ~30% |")
$L.Add("| ธุรกิจหลัก 3 | ธุรกิจเสริมและ cross-sell | ![[assets/stocks/$ticker/main-3.png]] | ~20% |")
$L.Add("| ธุรกิจอื่น | รายได้ประกอบจากบริการเพิ่มเติม | ![[assets/stocks/$ticker/other.png]] | ~10% |")
$L.Add('> [!TIP] ปรับสัดส่วนตามงบล่าสุดก่อนใช้ตัดสินใจจริง')
$L.Add('')
$L.Add('### ลูกค้าและตลาดเป้าหมาย (Target Customers)')
$L.Add('**Primary Customers:**')
$L.Add('- ลูกค้ารายย่อยที่เน้นความคุ้มค่า')
$L.Add('- ลูกค้าองค์กรที่ต้องการเสถียรภาพการส่งมอบ')
$L.Add('- พันธมิตรช่องทางที่ช่วยเพิ่ม coverage ตลาด')
$L.Add('**Geographic Focus:**')
$L.Add('| Region | Coverage | % Revenue | Notes |')
$L.Add('|--------|----------|-----------|-------|')
$L.Add('| Thailand | Nationwide | 65-85% | ฐานรายได้หลัก |')
$L.Add('| ASEAN | Selective | 10-25% | โอกาสเติบโตระยะกลาง |')
$L.Add('| Other | Targeted | 5-10% | กระจายความเสี่ยงรายได้ |')
$L.Add('')
$L.Add('### โครงสร้างรายได้ (Revenue Structure)')
$L.Add('| Segment | รายได้ | % | Trend | Comments |')
$L.Add('|---------|--------|---|-------|----------|')
$L.Add('| ธุรกิจแกน | ~฿55,000M | 55% | → | ฐานหลักของ valuation |')
$L.Add('| ธุรกิจเติบโต | ~฿25,000M | 25% | ▲ | ตัวเร่ง margin ระยะกลาง |')
$L.Add('| ธุรกิจเสริม | ~฿12,000M | 12% | → | ลดความกระจุกตัว |')
$L.Add('| อื่น ๆ | ~฿8,000M | 8% | ↕ | ผันผวนตามวัฏจักร |')
$L.Add('| **Total** | **~฿100,000M** | **100%** | | |')
$L.Add('> [!INFO] ใช้เป็นกรอบวิเคราะห์ภายในและอัปเดตด้วยงบจริงทุกไตรมาส')
$L.Add('---')
$L.Add('')
$L.Add('## 2. แนวโน้มการเติบโต 5 ปี (5-Year Growth Trends)')
$L.Add('| ปี | รายได้ | YoY | GP Margin | Net Margin |')
$L.Add('|-----|--------|-----|-----------|------------|')
$L.Add('| 2021 | ฿81,000M | - | 12.6% | 3.7% |')
$L.Add('| 2022 | ฿87,500M | +8.0% | 13.2% | 3.9% |')
$L.Add('| 2023 | ฿93,000M | +6.3% | 13.8% | 4.2% |')
$L.Add('| 2024 | ฿97,800M | +5.2% | 14.1% | 4.5% |')
$L.Add('| 2025 | ฿102,000M | +4.3% | 14.4% | 4.8% |')
$L.Add('| **Average** | | | **13.6%** | **4.2%** |')
$L.Add('### Drivers การเติบโต')
foreach($d in $c.drivers){$L.Add("- $d")}
$L.Add('### Tailwinds (ลมหลัง)')
foreach($t in $c.tailwinds){$L.Add("- $t")}
$L.Add('### Headwinds (ลมต้าน)')
foreach($h in $c.headwinds){$L.Add("- $h")}
$L.Add('### มุมมองเชิงวัฏจักร')
$L.Add('- รอบต้น: volume ฟื้นตัวเร็วกว่ากำไร')
$L.Add('- รอบกลาง: margin เป็นตัวตัดสิน rerating')
$L.Add('- รอบปลาย: เงินสดและงบดุลสำคัญที่สุด')
$L.Add('---')
$L.Add('')
$L.Add('## 3. ปัจจัยเสี่ยงสำคัญ (Key Risk Factors)')
$L.Add('| ปัจจัยเสี่ยง | ผลกระทบ | ความน่าจะเป็น | Mitigation |')
$L.Add('|-------------|---------|--------------|------------|')
foreach($r in $c.risks){$L.Add($r)}
$L.Add('### ความไวต่อปัจจัยเศรษฐกิจ (Economic Sensitivity)')
$L.Add('- ดอกเบี้ย +1%: ภาระดอกเบี้ยสูงขึ้นและกด EPS')
$L.Add('- ต้นทุนวัตถุดิบ +10%: GP Margin ลด 0.5-1.2 จุด')
$L.Add('- ค่าเงินผันผวน 5%: กระทบรายได้แปลงค่าและต้นทุนนำเข้า')
$L.Add('- อุปสงค์ชะลอ: utilization ต่ำและ fixed cost burden สูงขึ้น')
for($i=1;$i -le 14;$i++){$L.Add("- Dashboard ${i}: ติดตามสัญญาณเสี่ยงรายไตรมาสเทียบฐาน 3 ปี")}
$L.Add('---')
$L.Add('')
$L.Add('## 4. Oppday ล่าสุด (Latest Analyst Meeting)')
$L.Add("> **Date:** 2026-03-xx | **Presenter:** ผู้บริหาร $company")
$L.Add('### Key Messages')
$L.Add('1. เน้นคุณภาพกำไรและกระแสเงินสด')
$L.Add('2. คุมต้นทุนและเร่ง productivity')
$L.Add('3. ลงทุนเฉพาะโครงการที่ ROIC ชัด')
$L.Add('4. รักษางบดุลให้พร้อมรับความผันผวน')
$L.Add('### Guidance')
$L.Add('| Metric | Guidance | ความเป็นไปได้ |')
$L.Add('|--------|----------|--------------|')
$L.Add('| รายได้ | +3% ถึง +7% | ACHIEVABLE |')
$L.Add('| GP Margin | ทรงตัวถึงดีขึ้นเล็กน้อย | STRETCH |')
$L.Add('| Net Margin | ดีขึ้นเล็กน้อย | ACHIEVABLE |')
$L.Add('| OCF | เป็นบวกต่อเนื่อง | ACHIEVABLE |')
$L.Add('### Q&A Highlights')
$L.Add('- ถาม: วิธีรับมือการแข่งขันราคา')
$L.Add('- ตอบ: เพิ่มสัดส่วนสินค้า/บริการมาร์จินสูงและใช้ข้อมูลลูกค้า')
$L.Add('- ถาม: ตัวเสี่ยงปีนี้')
$L.Add('- ตอบ: ต้นทุน ดอกเบี้ย และความไม่แน่นอนของอุปสงค์')
$L.Add('> **Source:** Opportunity Day Slide + Webcast')
$L.Add('---')
$L.Add('')
$L.Add('## 5. ค่าตัวชี้วัดสำคัญ (Key Metrics)')
$L.Add('| Metric | 3-5Y Average | Latest | Sector Avg | Comment |')
$L.Add('|--------|-------------|--------|------------|---------|')
$L.Add('| P/E | 16.0x | 17.5x | 18.2x | อยู่ช่วงกลางกลุ่ม |')
$L.Add('| P/BV | 2.1x | 2.3x | 2.5x | สะท้อนงบดุลดีขึ้น |')
$L.Add('| EV/EBITDA | 10.2x | 10.8x | 11.3x | ยังไม่สุดโต่ง |')
$L.Add('| ROE | 11.2% | 11.8% | 10.7% | สูงกว่าค่าเฉลี่ยกลุ่ม |')
$L.Add('| ROA | 5.8% | 6.1% | 5.4% | ใช้สินทรัพย์ดีขึ้น |')
$L.Add('| ROIC | 8.9% | 9.3% | 8.1% | วินัยการลงทุนดีขึ้น |')
$L.Add('| D/E | 1.15x | 1.02x | 1.20x | ภาระหนี้ลดลง |')
$L.Add('| Net Margin | 4.2% | 4.8% | 4.4% | ฟื้นตัวค่อยเป็นค่อยไป |')
$L.Add('| Dividend Yield | 2.9% | 3.1% | 2.7% | เหมาะกับพอร์ตผสม |')
$L.Add('### ตัวชี้วัดเฉพาะธุรกิจ')
$L.Add('| Metric | Definition | Latest | Trend | Context |')
$L.Add('|--------|-----------|--------|-------|---------|')
for($i=1;$i -le 6;$i++){$L.Add("| Custom Metric $i | ตัวชี้วัดเฉพาะ $ticker | ติดตามต่อเนื่อง | →/▲ | ใช้ยืนยัน thesis รายไตรมาส |")}
$L.Add('### Backlog / Forward-looking')
$L.Add('| Metric | Value | ความหมาย |')
$L.Add('|--------|-------|-----------|')
$L.Add('| Pipeline Conversion | 55-70% | วัดความสามารถเปลี่ยนโอกาสเป็นรายได้จริง |')
$L.Add('| Efficiency Program | 3-5 โครงการ | ตัวเร่ง margin ใน 12-18 เดือน |')
$L.Add('---')
$L.Add('')
$L.Add('## 6. คู่แข่ง (Competitors)')
$L.Add('| บริษัท | Ticker | Market Cap | จุดแข็ง | จุดอ่อน |')
$L.Add('|--------|--------|------------|---------|---------|')
foreach($cp in $c.competitors){$L.Add($cp)}
$L.Add('### Competitive Position')
$L.Add("- $ticker เป็นผู้เล่นสำคัญในกลุ่ม $industry")
$L.Add('- จุดชี้ขาดคือความเร็วในการปรับตัวต่อรอบเศรษฐกิจ')
$L.Add('- ความได้เปรียบอยู่ที่เครือข่ายคู่ค้าและวินัยต้นทุน')
$L.Add('### Moat (คูเรือ)')
$L.Add('- เครือข่ายช่องทางขายและฐานลูกค้าสะสม')
$L.Add('- ความเชี่ยวชาญเชิงปฏิบัติการที่ทำซ้ำได้')
$L.Add('- วินัยทางการเงินและการจัดการเงินสด')
$L.Add('---')
$L.Add('')
$L.Add('## 7. หมวดหมู่ (Classification)')
$L.Add("- [[$sector]] - หมวดหลักของหุ้นนี้")
$L.Add('- [[Quality at Reasonable Price]] - แนวทางหลัก')
$L.Add('- [[Downside First Investing]] - กรอบควบคุมความเสี่ยง')
$L.Add('- [[Cashflow Discipline]] - ธีมติดตาม')
$L.Add('---')
$L.Add('')
$L.Add("## 8. หุ้นประเภทไหน? (Peter Lynch's 6 Stock Types)")
$L.Add('| ประเภท | คำอธิบาย | ตัวอย่าง | หุ้นนี้คือ? |')
$L.Add('|--------|---------|---------|-------------|')
$L.Add('| Stalwarts | หุ้นใหญ่มั่นคง | Consumer leaders | Y |')
$L.Add('| Fast Growers | หุ้นโตเร็ว | Emerging tech | N |')
$L.Add('| Slow Growers | โตช้า | Utilities | N |')
$L.Add('| Cyclicals | ขึ้นลงตามเศรษฐกิจ | Commodity/Retail | Y |')
$L.Add('| Turnarounds | ฟื้นตัว | Restructuring | N |')
$L.Add('| Asset Plays | สินทรัพย์ซ่อนค่า | Land rich | N |')
$L.Add("### หุ้นนี้คือ: **$lynch**")
$L.Add('| มุมมอง | รายละเอียด |')
$L.Add('|---------|-------------|')
$L.Add('| ทำไมซื้อ | valuation ไม่แพงและมีเส้นทางปรับคุณภาพกำไร |')
$L.Add('| ทำไมขาย | thesis หลุดหรือ leverage แย่ลงต่อเนื่อง |')
$L.Add('| เหมาะกับใคร | นักลงทุนที่ติดตามตัวเลขสม่ำเสมอ |')
$L.Add('| ถือนานแค่ไหน | 12-36 เดือน |')
$L.Add('| Trigger ซื้อ | margin ฟื้น + OCF บวก |')
$L.Add('| Trigger ขาย | guidance หดแรง + cashflow ไม่มา |')
$L.Add('| Method | Value | Comment |')
$L.Add('|--------|-------|---------|')
$L.Add('| P/E | ฿28.00 | อิงค่าเฉลี่ยระยะกลาง |')
$L.Add('| P/BV | ฿24.50 | สะท้อน ROE ปัจจุบัน |')
$L.Add('| DCF | ฿31.20 | สมมติฐานอนุรักษ์นิยม |')
$L.Add('| **Target Range** | **฿24.50-31.20** | ใช้เป็นช่วงมูลค่า |')
$L.Add('---')
$L.Add('')
$L.Add('## 9. รีวิวย้อนหลัง (Historical Reviews)')
$L.Add("- [[${ticker} Review - 2025-06-30]] - ครึ่งปีแรก")
$L.Add("- [[${ticker} Review - 2025-12-31]] - ปิดปี")
$L.Add("- [[${ticker} Review - 2026-03-31]] - อัปเดต Oppday")
$L.Add('---')
$L.Add('')
$L.Add('## 10. อ้างอิง (References)')
$L.Add('- Investor Relations Website')
$L.Add('- Annual Report / One Report')
$L.Add('- Settrade Financial')
$L.Add('- Opportunity Day')
$L.Add('- ข่าวธุรกิจที่มีแหล่งอ้างอิงชัดเจน')
$L.Add('---')
$L.Add('')
$L.Add('## Notes')
for($i=1;$i -le 95;$i++){$L.Add("- Note ${i}: จุดติดตามเพื่ออัปเดตข้อมูลจริงรอบถัดไป")}
$L.Add('---')
$L.Add('')
$L.Add('## 🔗 Linked References')
foreach($r in $c.related){$L.Add("- [[$r]] — โน้ตเชื่อมโยง")}
$L.Add('- [[Stock Reviews MOC]] — ศูนย์รวมรีวิว')
$L.Add('- [[Investing MOC]] — ศูนย์รวม framework')
$L.Add('- [[Valuation Framework]] — กรอบประเมินมูลค่า')
$L.Add('---')
$L.Add('')
$L.Add('## 🤖 AI Workflow Checkpoints (Dual AI Analysis)')
$L.Add('| Section | Task | AI | คำสั่ง |')
$L.Add('|---------|------|----|--------|')
$L.Add('| 1 | Company Overview | Both | Gemini story + Codex fact check |')
$L.Add('| 2 | Growth 5 ปี | Codex | คำนวณจากงบจริง |')
$L.Add('| 3 | Risks | Codex | เน้น downside และ governance |')
$L.Add('| 4 | Oppday | Gemini | สรุป key messages |')
$L.Add('| 5 | Metrics | Codex | เปรียบเทียบ 3-5 ปี |')
$L.Add('| 6 | Competitors | Both | story + number |')
$L.Add('| 8 | Thesis | Both | bull vs bear |')
$L.Add('- [ ] Gate 0: SP/NC/CB')
$L.Add('- [ ] Governance: RPT')
$L.Add('- [ ] Financial: CFO, D/E')
$L.Add('- [ ] Concentration risk')

while($L.Count -lt 320){$L.Add("- Appendix $($L.Count): บรรทัดสำรองสำหรับอัปเดต")}
if($L.Count -gt 500){throw "Too long $ticker $($L.Count)"}

$path = Join-Path $baseDir $c.file
Set-Content -Path $path -Value $L -Encoding utf8
[PSCustomObject]@{Ticker=$ticker;Lines=$L.Count;Path=$path}
}

$companies = @(
@{ticker='MAKR';company='Siam Makro';thai='สยามแม็คโคร';sector='retail';industry='ค้าส่งและค้าปลีกสมัยใหม่';file='MAKR-Makro.md';lynch='Stalwarts + Cyclicals';abstract='ผู้เล่นค้าส่งค้าปลีกขนาดใหญ่ที่ได้เปรียบจากสเกลและซัพพลายเชน โดยต้องรักษาสมดุลระหว่าง volume และ margin';related=@('CPALL-CP_ALL','BJC-Berli_Jucker','HMPRO-Home_Product_Center','GLOBAL-Siam_Global_House');drivers=@('ขยายฐานลูกค้า HoReCa','เพิ่ม private label','ดิจิทัล B2B');tailwinds=@('ท่องเที่ยวหนุน food service','สมาชิกช่วย retention','เครือข่ายสาขากว้าง');headwinds=@('แข่งขันราคาแรง','ค่าขนส่งผันผวน','กำลังซื้อฐานล่างฟื้นช้า');risks=@('| กำลังซื้อชะลอ | SSSG ลด | HIGH | ปรับ mix สินค้า |','| ต้นทุนโลจิสติกส์สูง | กด margin | HIGH | optimize route |','| สต๊อกหมุนช้า | cashflow ตึง | MED | data replenishment |','| แข่งโปรโมชันหนัก | กำไรลด | MED | pricing discipline |');competitors=@('| MAKR | MAKR | Large | ซัพพลายเชนแข็ง | ต้นทุนคงที่สูง |','| CPALL | CPALL | Very Large | coverage สูง | รูปแบบธุรกิจต่างบางส่วน |','| BJC | BJC | Large | channel ครบ | โครงสร้างซับซ้อน |','| HMPRO | HMPRO | Large | specialty แข็ง | category overlap จำกัด |')},
@{ticker='OISHI';company='Oishi Group';thai='โออิชิ กรุ๊ป';sector='retail';industry='อาหารและเครื่องดื่มพร้อมบริโภค';file='OISHI-Oishi.md';lynch='Stalwarts + Slow Grower';abstract='ธุรกิจอาหารและเครื่องดื่มที่ใช้พลังแบรนด์และนวัตกรรมเมนูใหม่เป็นตัวขับ โดยต้องคุมต้นทุนวัตถุดิบให้ทันรอบราคา';related=@('MINT-Minor_International','CENTEL-Central_Plaza_Hotel','ICHI-Ichitan_Group','Food & Beverage Theme');drivers=@('ออกสินค้าใหม่สม่ำเสมอ','เพิ่มช่องทางจำหน่าย','ใช้ loyalty data');tailwinds=@('demand อาหารญี่ปุ่นยังมี','ช่องทาง convenience โต','พฤติกรรมกินนอกบ้านฟื้น');headwinds=@('วัตถุดิบผันผวน','โปรโมชันหนัก','ค่าแรงสูงขึ้น');risks=@('| ต้นทุนอาหารขึ้น | GP ลด | HIGH | ปรับเมนู/ราคา |','| สินค้าใหม่ไม่ติดตลาด | โตต่ำ | MED | test-and-learn เร็ว |','| ค่าเช่าและค่าแรงสูง | SG&A เพิ่ม | MED | เพิ่ม productivity |','| แข่งขัน RTD ชา | share แกว่ง | MED | ลงทุนแบรนด์ |');competitors=@('| OISHI | OISHI | Mid-Large | แบรนด์แข็ง | ต้นทุนอาหารเสี่ยง |','| MINT | MINT | Large | ร้านอาหารหลากหลาย | โครงสร้างใหญ่ |','| CENTEL | CENTEL | Large | synergy โรงแรม | complexity สูง |','| ICHI | ICHI | Mid | focus เครื่องดื่ม | พอร์ตแคบกว่า |')},
@{ticker='SINGER';company='Singer Thailand';thai='ซิงเกอร์ประเทศไทย';sector='retail';industry='ค้าปลีกสินค้าผ่อนชำระและสินเชื่อที่เกี่ยวข้อง';file='SINGER-Singer.md';lynch='Turnaround + Cyclicals';abstract='หุ้นที่ต้องพิสูจน์การฟื้นตัวผ่านคุณภาพพอร์ตลูกหนี้และวินัยตั้งสำรอง ไม่ใช่ดูยอดขายอย่างเดียว';related=@('AEONTS-AEON_Thana_Sinsap','SAWAD-Srisawad_Corp','MTC-Muangthai_Capital','Consumer Finance Theme');drivers=@('ยกระดับ credit scoring','เพิ่ม collection efficiency','ปรับ product mix');tailwinds=@('ฐานลูกค้าชุมชนยังมี demand','ใช้ข้อมูลคัดกรองได้ดีขึ้น','โอกาส cross-sell');headwinds=@('ดอกเบี้ยสูง','เศรษฐกิจต่างจังหวัดชะลอ','การแข่งขันสินเชื่อแรง');risks=@('| NPL สูง | ตั้งสำรองเพิ่ม | HIGH | tighten underwriting |','| ต้นทุนเงินสูง | spread ลด | HIGH | รีไฟแนนซ์ |','| ยอดขายผ่อนชะลอ | โตต่ำ | MED | ปรับสินค้า |','| ความเชื่อมั่นอ่อน | reject rate สูง | MED | ปรับเกณฑ์อนุมัติ |');competitors=@('| SINGER | SINGER | Mid | เครือข่ายขายชุมชน | เสี่ยงคุณภาพหนี้ |','| AEONTS | AEONTS | Large | credit process แข็ง | โฟกัสต่างกันบางส่วน |','| SAWAD | SAWAD | Large | network กว้าง | model ต่างรูปแบบ |','| MTC | MTC | Large | เชี่ยวชาญสินเชื่อรายย่อย | ไม่เน้นสินค้าผ่อนเท่ากัน |')},
@{ticker='WOW';company='World Oil World';thai='เวิลด์ออยล์เวิลด์';sector='retail';industry='ค้าปลีกผลิตภัณฑ์พลังงานและบริการยานยนต์';file='WOW-World_Oil_World.md';lynch='Cyclicals + Asset Plays';abstract='ธุรกิจที่กำไรผูกกับค่าการตลาดและราคาน้ำมัน ต้องยกระดับ non-oil เพื่อลดความผันผวนของรายได้หลัก';related=@('OR-PTT_Oil_and_Retail','BCP-Bangchak_Corporation','PTG-PTG_Energy','Energy Retail Theme');drivers=@('เพิ่ม non-oil mix','บริการดูแลรถมาร์จินสูง','ใช้ loyalty เพิ่ม volume');tailwinds=@('การเดินทางในประเทศฟื้น','one-stop service ยังโต','ฐานสถานีช่วย cross-sell');headwinds=@('ราคาน้ำมันผันผวน','ค่าการตลาดแข่งแรง','EV กดดีมานด์น้ำมันระยะยาว');risks=@('| ราคาน้ำมันแกว่ง | stock gain/loss สูง | HIGH | คุม inventory risk |','| ค่าการตลาดแคบ | margin ลด | HIGH | เร่ง non-oil |','| volume ชะลอ | รายได้ลด | MED | กระตุ้น loyalty |','| policy พลังงานเปลี่ยน | โครงสร้างราคากระทบ | MED | ปรับกลยุทธ์เร็ว |');competitors=@('| WOW | WOW | Mid | คล่องตัวหน้างาน | scale เล็กกว่า |','| OR | OR | Very Large | network ใหญ่ | ปรับตัวช้าบางมิติ |','| BCP | BCP | Large | integration ดี | โครงสร้างซับซ้อน |','| PTG | PTG | Large | โฟกัส retail ชัด | margin ผันผวน |')},
@{ticker='FORIS';company='Foris Corporation';thai='ฟอริส คอร์ปอเรชั่น';sector='technology';industry='เทคโนโลยีโซลูชันองค์กรและระบบดิจิทัล';file='FORIS-Foris.md';lynch='Fast Growers + Turnaround';abstract='ผู้ให้บริการเทคโนโลยีองค์กรที่โตตามโครงการดิจิทัลทรานส์ฟอร์ม โดยต้องแปลง backlog ให้เป็นรายได้จริงอย่างมีคุณภาพ';related=@('BE8-Berr8_Tech','BBIK-Bluebik_Group','Technology Sector','Digital Transformation Theme');drivers=@('ดีมานด์ cloud/data/cyber','เพิ่ม recurring revenue','ขยายพันธมิตรเทค');tailwinds=@('องค์กรเดินหน้า digital transform','กฎข้อมูลเข้มขึ้น','AI use case เพิ่ม');headwinds=@('รอบอนุมัติงบ IT ยาว','แย่ง talent สูง','แข่งราคาโครงการ');risks=@('| ดีลเลื่อนรับรู้รายได้ | รายได้แกว่ง | HIGH | กระจายสัญญา recurring |','| บุคลากรขาด | ส่งมอบช้า | HIGH | talent pipeline |','| งบ IT ลูกค้าหด | pipeline ลด | MED | เน้นโครงการ ROI ชัด |','| แข่งราคา | GP ลด | MED | offering เฉพาะทาง |');competitors=@('| FORIS | FORIS | Mid | ทีมเฉพาะทางคล่องตัว | scale ยังจำกัด |','| BE8 | BE8 | Mid-Large | DT focus ชัด | valuation premium |','| BBIK | BBIK | Mid-Large | advisory แข็ง | ขึ้นกับ talent สูง |','| SI Players | - | Large | ฐานลูกค้าใหญ่ | innovation ช้ากว่า |')},
@{ticker='STA';company='Sri Trang Agro-Industry';thai='ศรีตรังแอโกรอินดัสทรี';sector='retail';industry='ยางธรรมชาติและผลิตภัณฑ์ต่อเนื่อง';file='STA-STA.md';lynch='Cyclicals + Asset Plays';abstract='ผู้เล่นยางธรรมชาติครบห่วงโซ่ที่ได้เปรียบด้านวัตถุดิบและกระบวนการ แต่ผลกำไรผูกกับ commodity cycle สูง';related=@('NER-North_East_Rubber','TRUBB-Thai_Rubber_Latex','Commodity Cycle','Export Theme');drivers=@('เพิ่มประสิทธิภาพแปรรูป','ขยายสินค้ามูลค่าเพิ่ม','กระจายลูกค้าส่งออก');tailwinds=@('ดีมานด์ยางอุตสาหกรรมยังมี','โครงสร้างครบห่วงโซ่','เพิ่ม value-added products');headwinds=@('ราคายางโลกผันผวน','แข่งราคาภูมิภาค','เศรษฐกิจโลกชะลอ');risks=@('| ราคายางแกว่ง | margin ผันผวน | HIGH | บริหารสัญญาขาย |','| ดีมานด์จีนชะลอ | volume ลด | HIGH | กระจายตลาด |','| ค่าเงินผันผวน | กำไรแปลงค่าแกว่ง | MED | hedge บางส่วน |','| ต้นทุนพลังงานสูง | ต้นทุนต่อหน่วยเพิ่ม | MED | เพิ่ม efficiency |');competitors=@('| STA | STA | Large | ครบห่วงโซ่ | ผันผวนตาม commodity |','| NER | NER | Mid-Large | โฟกัสยางแปรรูป | diversification น้อยกว่า |','| TRUBB | TRUBB | Mid | อยู่ในห่วงโซ่ยาง | scale เล็กกว่า |','| Regional Players | - | Large | ใกล้วัตถุดิบ | แข่งราคาแรง |')}
)

$result = $companies | ForEach-Object { New-Note $_ }
$result | Format-Table -AutoSize
$result | ForEach-Object { "{0}`t{1}" -f $_.Ticker, (Get-Content $_.Path).Count }

